### ISSUE TITLE
Chaining promises is not possible as expected.

### ISSUE THREAD

**Issue by hickscorp** [jclem/q-defer#2]
When using the Q javascript standard library (And pretty much any other lib i have tried), the behavior is:
```coffee
somethingGivingMeAPromise()
.then (res) ->
  anotherMethodReturningAPromise(res)
.then (res) ->
  anotherLastMethodReturningAPromise(res)
```
The previous snipet would:

- Call somethingGivingMeAPromise(), and wait for the result. Pass it to the first then() callback.
- Call anotherMethodReturningAPromise() method, and wait for the result, pass the result to the next then() callback.
- And so on.

With this ruby `q-defer` implementation, it appears that i have to:
```ruby
somethingGivingMeAPromise
.then do |res|
  anotherMethodReturningAPromise(res)
  .then (res) do |res|
    anotherLastMethodReturningAPromise(res)
  end
end
```

This makes no sense to me, as the Q principles is to avoid callback spaguetti, and to be able to catch() any failure in the last catch() block (Which is not the case here).

What am i missing here?

**Comment by hickscorp** [comment]
A reproducible example of what i'm talking about:

```ruby
def first
  Q.defer do |d|
    d.resolve 'Result from first.'
  end
end
def second
  Q.defer do |d|
    d.resolve 'Result from second.'
  end
end
def third
  Q.defer do |d|
    d.resolve 'Result from third.'
  end
end
```

One would expect this to be callable by doing:

```ruby
first
.then do |first_res|
  puts first_res
  second
end
.then do |second_res|
  puts second_res
  third
end
.then do |third_res|
  puts third_res
end
```

But this doesn't work, the output is:
```log
Result from first.
Result from first.
Result from first.
```

To have the right behavior, I have to do:

```ruby
first
.then do |first_res|
  puts first_res
  second
  .then do |second_res|
    puts second_res
    third
    .then do |third_res|
      puts third_res
    end
  end
end
```

Then i can get the expected output: 

```log
Result from first.
Result from second.
Result from third.
```

So really, what is the purpose of q-defer vs passing blocks around?

**Comment by hickscorp** [comment]
Dead repo?

**Comment by jclem** [comment]
@hickscorp Yeah, very much so.
